### ISSUE TITLE
smart-character refactor into non-root module

### ISSUE THREAD

**Issue by MerkleBoy** [projectawakening/world-chain-contracts#14] opened 2024-03-04 17:40 UTC
following discussion from #10 :

https://github.com/ccpgames/eve-frontier-game-chain-contracts/pull/10#discussion_r1505689851

**Comment by tinkrtailor** [comment] 2024-09-11 11:01
Closed as a duplicate of https://github.com/projectawakening/world-chain-contracts/issues/8

**Closed by tinkrtailor** 2024-09-11 11:01 UTC
